### ISSUE TITLE
Event logging does weird things

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#27] opened 2017-02-15 13:55 UTC
![image](https://cloud.githubusercontent.com/assets/1858302/22977205/ab27a48e-f3c8-11e6-9037-e6e5fd1e1f22.png)

Firstly - the log does not know what to expect in the "callee" contract for cb
![image](https://cloud.githubusercontent.com/assets/1858302/22977278/e8f6452c-f3c8-11e6-8e65-e82f18078408.png)
and c4 fails to log the string
(note - it gets msg.sender correct)

![image](https://cloud.githubusercontent.com/assets/1858302/22977321/206a5660-f3c9-11e6-80e1-b35b2e2b10df.png)
The strings (when shown as strings) for cb are somewhat weird
![image](https://cloud.githubusercontent.com/assets/1858302/22977345/3b9bafa6-f3c9-11e6-8074-6f2304959e1d.png)
![image](https://cloud.githubusercontent.com/assets/1858302/22977361/4e20abcc-f3c9-11e6-8a2a-bec6c19ce5c2.png)

**Comment by asinyagin** [comment] 2017-02-16 11:54
I think that's a duplicate of #24. There's some changes in storing of event data.

**Closed by asinyagin** 2017-02-16 11:54 UTC
