### ISSUE TITLE
Variables not initialised correctly; (Add a warning message)

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#54] opened 2017-02-22 18:11 UTC
"A variable which is declared will have an initial default value whose byte-representation is all zeros. The “default values” of variables are the typical “zero-state” of whatever the type is. For example, the default value for a bool is false. The default value for the uint or int types is 0. For statically-sized arrays and bytes1 to bytes32, each individual element will be initialized to the default value corresponding to its type. Finally, for dynamically-sized arrays, bytes and string, the default value is an empty array or string."

```
pragma solidity ^0.4.0;

contract prices {
    
    uint16  constant public numDP = 30;
    uint256 constant public TenToPowerThirty = 10 ** 30;
    //                                                    123456789012345678901234567890
    uint256  constant public ZeroPointNineNineFive =     995000000000000000000000000000;
    uint256  constant public OnePointZeroZeroSevenNine = 1007900000000000000000000000000;

    
    uint256  public buyGold;               // Gold Price in SGD
    uint256  public sellGold;
    uint256  public spotGold;              // Gold Price in SGD
    
    event spot(uint256);
    
    function setGoldPrices(uint256 buy, uint256 sell) 
	{
        buyGold = buy;
		sellGold = sell;
        uint256 buySpot = buyGold * TenToPowerThirty / OnePointZeroZeroSevenNine ;
        uint256 sellSpot = sellGold * TenToPowerThirty / ZeroPointNineNineFive ;
        spotGold = (buySpot + sellSpot) / 2; 
        spot(spotGold);
	}
  

}
```
![image](https://cloud.githubusercontent.com/assets/1858302/23225418/d1793b62-f96c-11e6-8ca0-a0d1629b90ee.png)

![image](https://cloud.githubusercontent.com/assets/1858302/23225444/e4acb402-f96c-11e6-9fba-96cde2adc108.png)

![image](https://cloud.githubusercontent.com/assets/1858302/23225475/fefb53cc-f96c-11e6-8afd-a8093d76e14a.png)

first time hitting the breakpoint
![image](https://cloud.githubusercontent.com/assets/1858302/23225567/41ff83aa-f96d-11e6-80b1-1eac2936e35b.png)

![image](https://cloud.githubusercontent.com/assets/1858302/23225559/35e19040-f96d-11e6-84c6-290ed7882c55.png)

**Comment by asinyagin** [comment] 2017-02-23 11:03
Need to investigate that, but I think that's a duplicate of #52. The contract has a weird storage.

**Comment by romanman** [comment] 2017-02-27 14:41
more info on #51 (duplicate)

**Comment by romanman** [comment] 2017-03-03 14:11
@DaveAppleton : fixed and deployed. Check it please.

**Closed** 2017-03-03 14:11 UTC
Labels: bug, coins-approved
