### ISSUE TITLE
Debugger Local Variables are not showing execute state in constructor

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#42] opened 2017-02-17 14:18 UTC
Use the following contract, place a stop in A constructor second line. Check local variables and will be 0, not 7.
Try calling the function t2, the local variables will show correct expected values.
```
pragma solidity ^0.4.2;

import "lib/std.sol";

contract A { 
 uint public num;
 event aNum(string n, uint x);
  function A(uint x){
    aNum("A(uint)",x);
    num = x;  
  }
  function t2(uint x){
    aNum("t2(uint)",x);
    num = x;  
  }
}

contract B is A{
    function B() A(7){   
    } 
}
```

![image](https://cloud.githubusercontent.com/assets/224810/23068430/71ef1748-f502-11e6-9a43-29c80b5c1537.png)

**Comment by asinyagin** [comment] 2017-02-21 09:00
It's a duplicate of #40. Solc generates weird code for constructors.

**Comment by romanman** [comment] 2017-02-21 09:13
@asinyagin : can we close the dup?

**Closed** 2017-02-21 10:15 UTC
Labels: duplicate, in-reveiw
