### ISSUE TITLE
array.length not reported correctly?

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#50] opened 2017-02-21 19:59 UTC
```
pragma solidity ^0.4.0;

contract babyFace {

    address[]  arrayOfL;
        
    function len() constant returns (uint256) {
        return arrayOfL.length;
    }
    
}


```

![image](https://cloud.githubusercontent.com/assets/1858302/23182344/33a1dc64-f8b3-11e6-8cc8-49b9c77c9db4.png)

**Comment by asinyagin** [comment] 2017-02-22 17:59
Duplicate of #51.

**Closed by asinyagin** 2017-02-22 17:59 UTC
Labels: in-reveiw
