### ISSUE TITLE
Debugger step over some lines and refuses to break on them

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#44] opened 2017-02-17 15:28 UTC
The following lines are ignored by debugger
![image](https://cloud.githubusercontent.com/assets/224810/23071208/bbeb04b2-f514-11e6-8490-11c3e848b471.png)

Executing this with debugger will not break at all.

This will break debugger at correct line, but if we step into, it will go directly to line 15
![image](https://cloud.githubusercontent.com/assets/224810/23071264/d98ab148-f514-11e6-9cf7-f871e1391475.png)

```
pragma solidity ^0.4.2;

contract A {
 
 uint public num;
 event aNum(string n, uint x);
  function A(uint x){
    aNum("A(uint)",x);
    num = x;  
    x++;
    num++;
    x++;
    num++;
    x++;
    aNum("A(uint) [2]",x);
  }
  
  function t2(uint x){
    aNum("t2(uint)",x);
    num = x;  
    x++;
    num++;
    x++;
    num++;
    x++;
  }

}

contract B is A{
    
    function B() A(7){
        
    }
    
}
```

**Comment by asinyagin** [comment] 2017-02-21 09:12
Duplicate of #40

**Comment by asinyagin** [comment] 2017-02-21 09:12
Solc generates weird code for constructors

**Comment by romanman** [comment] 2017-02-21 09:13
@asinyagin : can we close the dup?

**Closed** 2017-02-21 10:15 UTC
Labels: duplicate, in-reveiw
